extends SceneTree
## Writes data/roster/enemies.csv and elites.csv from the current data/enemies and data/elites
## .tres files (bosses.csv is hand-written), and data/roster/README.md's trait list from the trait
## scripts. Run: godot --headless -s res://tools/roster_export.gd
## Only settings that differ from a trait's defaults are written.

const ENEMY_COLUMNS := ["id", "visual", "scale", "tint", "brain", "hp", "speed", "score", "dive_score", "bullet_speed", "scrap_chance", "scrap", "can_capture", "traits"]
const ELITE_COLUMNS := ["id", "name", "hint", "visual", "scale", "tint", "hp", "score", "scrap", "speed", "fire_interval", "fan_shots", "bullet_speed", "traits"]


func _process(_delta: float) -> bool:
	var roster: Node = root.get_node("Roster")
	_write("res://data/roster/enemies.csv", ENEMY_COLUMNS, _defs("res://data/enemies/"), roster.ENEMY_TRAITS)
	_write("res://data/roster/elites.csv", ELITE_COLUMNS, _defs("res://data/elites/"), roster.ELITE_TRAITS)
	_write_traits("res://data/roster/TRAITS.md", roster.ENEMY_TRAITS, roster.ELITE_TRAITS)
	return true


func _defs(dir: String) -> Array[Resource]:
	var defs: Array[Resource] = []
	for file in DirAccess.get_files_at(dir):
		if file.ends_with(".tres"):
			defs.append(load(dir + file))
	return defs


func _write(path: String, columns: Array, defs: Array[Resource], registry: Dictionary) -> void:
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_csv_line(PackedStringArray(columns))
	for def in defs:
		var cells := PackedStringArray()
		for column: String in columns:
			cells.append(_cell(def, column, registry))
		file.store_csv_line(cells)
	print("wrote ", path, " (", defs.size(), " rows)")


## A reference of every trait: what it does (the script's doc comment) and its settings.
func _write_traits(path: String, enemy_traits: Dictionary, elite_traits: Dictionary) -> void:
	var lines := PackedStringArray(["# Traits", "", "Generated by tools/roster_export.gd from the trait scripts. Use these names and settings in the `traits` and `phases` columns.", ""])
	for section: Array in [["Enemy traits (enemies.csv)", enemy_traits], ["Elite and boss traits (elites.csv, bosses.csv)", elite_traits]]:
		lines.append("## " + section[0])
		lines.append("")
		var registry: Dictionary = section[1]
		var names := registry.keys()
		names.sort()
		for name: String in names:
			var script: Script = load(registry[name])
			lines.append("### " + name)
			lines.append(_doc(registry[name]))
			lines.append("")
			var t: Object = script.new()
			for info in t.get_property_list():
				if info["usage"] & PROPERTY_USAGE_SCRIPT_VARIABLE and info["usage"] & PROPERTY_USAGE_STORAGE:
					var value: Variant = t.get(info["name"])
					if not (value is Resource) or "/data/" in (value as Resource).resource_path:
						lines.append("- `%s` = %s" % [info["name"], _value(value)])
			lines.append("")
	FileAccess.open(path, FileAccess.WRITE).store_string("\n".join(lines))
	print("wrote ", path)


func _doc(script_path: String) -> String:
	var doc := PackedStringArray()
	for line in FileAccess.get_file_as_string(script_path).split("\n"):
		if line.begins_with("## "):
			doc.append(line.trim_prefix("## "))
		elif not doc.is_empty():
			break
	return " ".join(doc)


func _cell(def: Resource, column: String, registry: Dictionary) -> String:
	match column:
		"visual":
			return def.get("visual_scene").resource_path.get_file().get_basename()
		"brain":
			return def.get("brain").resource_path.get_file().get_basename()
		"scale":
			return _num(def.get("visual_scale"))
		"name":
			return def.get("display_name")
		"traits":
			var parts := PackedStringArray()
			var all: Array = def.call("all_traits") if def.has_method("all_traits") else def.call("traits_for_phase", -1)
			for t: Resource in all:
				parts.append(_trait(t, registry))
			return "; ".join(parts)
	return _value(def.get(column))


func _trait(t: Resource, registry: Dictionary) -> String:
	var name: String = registry.find_key(t.get_script().resource_path)
	var defaults: Object = t.get_script().new()
	var settings := PackedStringArray()
	for info in t.get_property_list():
		if not info["usage"] & PROPERTY_USAGE_SCRIPT_VARIABLE or not info["usage"] & PROPERTY_USAGE_STORAGE:
			continue
		var value: Variant = t.get(info["name"])
		if value != defaults.get(info["name"]):
			settings.append("%s=%s" % [info["name"], _value(value)])
	return name if settings.is_empty() else "%s(%s)" % [name, " ".join(settings)]


func _value(value: Variant) -> String:
	if value is Color:
		var c: Color = value
		return "%s %s %s" % [_num(c.r), _num(c.g), _num(c.b)] + ("" if c.a == 1.0 else " " + _num(c.a))
	if value is float:
		return _num(value)
	if value is Resource:
		var r: Resource = value
		var path := r.resource_path
		return path.get_file().get_basename() if "/data/enemies/" in path or "/data/brains/" in path else path
	return str(value)


func _num(x: float) -> String:
	return str(snappedf(x, 0.001))
